const questions = [
  {
    categoryName: "General Knowledge",
    difficulty: "easy",
    type: "multiple",
    question: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Venus", "Jupiter"],
    answer: "Mars",
    explanation: "Mars is called the Red Planet because of iron oxide on its surface.",
    points: 10,
  },
  {
    categoryName: "General Knowledge",
    difficulty: "easy",
    type: "boolean",
    question: "The Pacific Ocean is the largest ocean on Earth.",
    options: ["True", "False"],
    answer: "True",
    explanation: "The Pacific Ocean is the largest and deepest ocean on Earth.",
    points: 10,
  },
  {
    categoryName: "Science",
    difficulty: "easy",
    type: "multiple",
    question: "What gas do humans need to breathe to survive?",
    options: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
    answer: "Oxygen",
    explanation: "Humans need oxygen for respiration.",
    points: 10,
  },
  {
    categoryName: "Science",
    difficulty: "medium",
    type: "boolean",
    question: "Humans have four lungs.",
    options: ["True", "False"],
    answer: "False",
    explanation: "Humans have two lungs.",
    points: 10,
  },
  {
    categoryName: "Technology",
    difficulty: "easy",
    type: "multiple",
    question: "Which of these is a web browser?",
    options: ["Chrome", "Python", "Linux", "Photoshop"],
    answer: "Chrome",
    explanation: "Google Chrome is a web browser.",
    points: 10,
  },
  {
    categoryName: "Technology",
    difficulty: "medium",
    type: "boolean",
    question: "HTML is a programming language.",
    options: ["True", "False"],
    answer: "False",
    explanation: "HTML is a markup language, not a programming language.",
    points: 10,
  },
  {
    categoryName: "History",
    difficulty: "easy",
    type: "multiple",
    question: "Which country built the pyramids?",
    options: ["India", "Egypt", "China", "Greece"],
    answer: "Egypt",
    explanation: "The famous pyramids were built in ancient Egypt.",
    points: 10,
  },
  {
    categoryName: "History",
    difficulty: "medium",
    type: "boolean",
    question: "The Roman Empire existed before the Ottoman Empire.",
    options: ["True", "False"],
    answer: "True",
    explanation: "The Roman Empire came much earlier than the Ottoman Empire.",
    points: 10,
  },
  {
    categoryName: "Sports",
    difficulty: "easy",
    type: "multiple",
    question: "How many players are there in a football team on the field?",
    options: ["9", "10", "11", "12"],
    answer: "11",
    explanation: "A football team has 11 players on the field.",
    points: 10,
  },
  {
    categoryName: "Sports",
    difficulty: "medium",
    type: "boolean",
    question: "Basketball teams have 5 players on the court at a time.",
    options: ["True", "False"],
    answer: "True",
    explanation: "Each basketball team has 5 players on the court.",
    points: 10,
  }
];

export default questions;