const questions = [
  {
    categoryName: "General Knowledge",
    difficulty: "easy",
    type: "multiple",
    question: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Venus", "Jupiter"],
    answer: "Mars",
    explanation: "Mars is called the Red Planet because of iron oxide on its surface.",
    points: 10,
  },
  {
    categoryName: "General Knowledge",
    difficulty: "easy",
    type: "boolean",
    question: "The Pacific Ocean is the largest ocean on Earth.",
    options: ["True", "False"],
    answer: "True",
    explanation: "The Pacific Ocean is the largest and deepest ocean on Earth.",
    points: 10,
  },
  {
    categoryName: "General Knowledge",
    difficulty: "easy",
    type: "multiple",
    question: "What is the capital of France?",
    options: ["Paris", "Rome", "Madrid", "Berlin"],
    answer: "Paris",
    explanation: "Paris is the capital city of France.",
    points: 10,
  },
  {
    categoryName: "General Knowledge",
    difficulty: "medium",
    type: "multiple",
    question: "Which instrument has 88 keys?",
    options: ["Guitar", "Piano", "Violin", "Flute"],
    answer: "Piano",
    explanation: "A standard piano has 88 keys.",
    points: 10,
  },
  {
    categoryName: "General Knowledge",
    difficulty: "hard",
    type: "boolean",
    question: "Lightning never strikes the same place twice.",
    options: ["True", "False"],
    answer: "False",
    explanation: "Lightning can strike the same place multiple times, especially tall structures.",
    points: 10,
  },
  {
    categoryName: "Science",
    difficulty: "easy",
    type: "multiple",
    question: "What gas do humans need to breathe to survive?",
    options: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
    answer: "Oxygen",
    explanation: "Humans need oxygen for respiration.",
    points: 10,
  },
  {
    categoryName: "Science",
    difficulty: "medium",
    type: "boolean",
    question: "Humans have four lungs.",
    options: ["True", "False"],
    answer: "False",
    explanation: "Humans have two lungs.",
    points: 10,
  },
  {
    categoryName: "Technology",
    difficulty: "easy",
    type: "multiple",
    question: "Which of these is a web browser?",
    options: ["Chrome", "Python", "Linux", "Photoshop"],
    answer: "Chrome",
    explanation: "Google Chrome is a web browser.",
    points: 10,
  },
  {
    categoryName: "Technology",
    difficulty: "medium",
    type: "boolean",
    question: "HTML is a programming language.",
    options: ["True", "False"],
    answer: "False",
    explanation: "HTML is a markup language, not a programming language.",
    points: 10,
  },
  {
    categoryName: "History",
    difficulty: "easy",
    type: "multiple",
    question: "Which country built the pyramids?",
    options: ["India", "Egypt", "China", "Greece"],
    answer: "Egypt",
    explanation: "The famous pyramids were built in ancient Egypt.",
    points: 10,
  },
  {
    categoryName: "History",
    difficulty: "medium",
    type: "boolean",
    question: "The Roman Empire existed before the Ottoman Empire.",
    options: ["True", "False"],
    answer: "True",
    explanation: "The Roman Empire came much earlier than the Ottoman Empire.",
    points: 10,
  },
  {
    categoryName: "Sports",
    difficulty: "easy",
    type: "multiple",
    question: "How many players are there in a football team on the field?",
    options: ["9", "10", "11", "12"],
    answer: "11",
    explanation: "A football team has 11 players on the field.",
    points: 10,
  },
  {
    categoryName: "Sports",
    difficulty: "medium",
    type: "boolean",
    question: "Basketball teams have 5 players on the court at a time.",
    options: ["True", "False"],
    answer: "True",
    explanation: "Each basketball team has 5 players on the court.",
    points: 10,
  },
  {
    categoryName: "Science",
    difficulty: "easy",
    type: "boolean",
    question: "Water boils at 100°C at sea level.",
    options: ["True", "False"],
    answer: "True",
    explanation: "At standard atmospheric pressure, water boils at 100°C.",
    points: 10,
  },
  {
    categoryName: "Science",
    difficulty: "medium",
    type: "multiple",
    question: "What part of the cell contains most of the genetic material?",
    options: ["Ribosome", "Nucleus", "Cell membrane", "Golgi apparatus"],
    answer: "Nucleus",
    explanation: "In most cells, DNA is stored in the nucleus.",
    points: 10,
  },
  {
    categoryName: "Science",
    difficulty: "hard",
    type: "multiple",
    question: "What is the chemical symbol for potassium?",
    options: ["P", "Pt", "K", "Po"],
    answer: "K",
    explanation: "Potassium’s symbol is K (from Latin: kalium).",
    points: 10,
  },
  {
    categoryName: "Technology",
    difficulty: "easy",
    type: "boolean",
    question: "A byte is equal to 8 bits.",
    options: ["True", "False"],
    answer: "True",
    explanation: "1 byte = 8 bits.",
    points: 10,
  },
  {
    categoryName: "Technology",
    difficulty: "medium",
    type: "multiple",
    question: "Which HTTP method is typically used to update an existing resource?",
    options: ["GET", "POST", "PUT", "TRACE"],
    answer: "PUT",
    explanation: "PUT is commonly used to update/replace a resource.",
    points: 10,
  },
  {
    categoryName: "Technology",
    difficulty: "hard",
    type: "boolean",
    question: "In JavaScript, '===' performs type coercion before comparison.",
    options: ["True", "False"],
    answer: "False",
    explanation: "Strict equality (===) does not perform type coercion.",
    points: 10,
  },
  {
    categoryName: "History",
    difficulty: "easy",
    type: "boolean",
    question: "World War II ended in 1945.",
    options: ["True", "False"],
    answer: "True",
    explanation: "WWII ended in 1945.",
    points: 10,
  },
  {
    categoryName: "History",
    difficulty: "medium",
    type: "multiple",
    question: "Who was the first President of the United States?",
    options: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"],
    answer: "George Washington",
    explanation: "George Washington served as the first U.S. President.",
    points: 10,
  },
  {
    categoryName: "Sports",
    difficulty: "easy",
    type: "multiple",
    question: "In tennis, what is the score called when it is 40-40?",
    options: ["Match point", "Deuce", "Advantage", "Break point"],
    answer: "Deuce",
    explanation: "40-40 is called deuce.",
    points: 10,
  },
  {
    categoryName: "Sports",
    difficulty: "hard",
    type: "boolean",
    question: "The FIFA World Cup is held every 2 years.",
    options: ["True", "False"],
    answer: "False",
    explanation: "The FIFA World Cup is held every 4 years.",
    points: 10,
  }
];

export default questions;